### ISSUE TITLE
Require Users to Pass a Test Before Allowing Them to Ask Questions

### ISSUE THREAD

**Issue by MoonTM-GIT** [Java-Discord/JavaBot#127]
As this was a feature we were planning to implement in the now scrapped [JavaBot2](https://github.com/Java-Discord/JavaBot2), I added it here.

We should prevent users from using the help system unless they have passed a test indicating that they have read and understood the help guidelines and some basics of how to ask good questions.

Dan suggested that such a test should include the following:
- Formatting code (using triple backticks and syntax highlighting).
- Knowing how to use the help system.
- Knowing that Javascript is different from Java.

I suggest that we implement such a test in the following way:

1. A user sends a message in an available help channel. While reserving, we check if the user is not yet approved to ask questions. Continue to next step if not yet approved.
2. The bot reserves the channel anyways, and replies to the user with a question. The user must answer the question correctly to continue (clicking an interaction button, sending a valid message in the channel, etc.).
3. If the user answers all questions correctly, the channel is then kept reserved and the user's question can be asked. Otherwise, the bot tells the user to read the help guidelines and try again, and then unreserves the channel.

**Comment by MoonTM-GIT** [comment]
> Or we just wait until discord releases text interactions
> https://devsnek.notion.site/devsnek/Modal-aka-Form-Interactions-e839b3dd8c214eb08f950764a8328e36

@DynxstyGIT

**Comment by danthe1st** [comment]
> Knowing that Javascript is different from Java.

Maybe they should also proof that they know what java is in general. This could be done using a multiple choice question (selection menu) that includes `a game` so that we get rid of Minecraft questions, too.

**Comment by DynxstyGIT** [comment]
We decided to scrap this mechanic entirely, as it causes way too much confusion.
