### ISSUE TITLE
Broken Naming Conventions

### ISSUE THREAD

**Issue by DeveloperCallum** [Java-Discord/JavaBot#221]
1. **Describe the bug**
Interfaces are named using c# style.

3. **Expected behavior**
Remove all the I's from the interface class names and use the type.

4. **Additional context**
Just to make sure i wasn't going braindead and name it the descriptive noun.

https://stackoverflow.com/questions/2814805/java-interfaces-implementation-naming-convention

https://stackoverflow.com/questions/2814805/java-interfaces-implementation-naming-convention

**Comment by sahilasopa** [comment]
can you give examples of where they are used?

**Comment by DeveloperCallum** [comment]
![image](https://user-images.githubusercontent.com/47298501/154861800-912daac0-89ce-48d8-be68-dd114deb24a3.png)

**Comment by danthe1st** [comment]
The thing is, there isn't really a generally agreed convention for interface names in Java. It all depends on the project.

**Comment by DeveloperCallum** [comment]
docs.oracle says that "Interface names should be capitalized like class names." and class names aren't prefixed with `I` and they're also `nouns`. so, it is not safe to assume that they should not be prefixed with `I`.

Class names: "Class names should be `nouns`, in mixed case with the first letter of each `internal word` capitalized." 

`ICommand`m I is not part of the 'internal word'

**Comment by DeveloperCallum** [comment]
Just remove the `i`. the names are fine as they are, if you exclude it. they're pretty descriptive of their function so, just remove the `i` prefixes

**Comment by danthe1st** [comment]
I think this would collide with `JDA`s interfaces.

**Comment by DeveloperCallum** [comment]
Not from what I can see.

![image](https://user-images.githubusercontent.com/47298501/155850818-e6ea63c6-f20e-4b57-9bbd-3cb75b1b9eaa.png)

![image](https://user-images.githubusercontent.com/47298501/155850857-c1a901c4-f91c-44e3-bfd9-bdd3b263ab1c.png)


![image](https://user-images.githubusercontent.com/47298501/155850828-64e5fd82-8973-4476-b4e6-f9ab86cb13f8.png)

![image](https://user-images.githubusercontent.com/47298501/155850837-85b4c038-91ad-44d1-b123-ca3f1c29f17e.png)

**Comment by DynxstyGIT** [comment]
yup, I'll may change this when I'm home
