### ISSUE TITLE
Set reports as handled

### ISSUE THREAD

**Issue by DeveloperCallum** [Java-Discord/JavaBot#230]
**Is your feature request related to a problem? Please describe.**
It currently is impossable to tell if a report  has been handled by another user. this could cause multiple staff to handle the same request.

**Describe the solution you'd like**
if someone handles a report the embed is updated to say REPORT HANDLED BY X STAFF.

**Describe alternatives you've considered**
None.

**Comment by danthe1st** [comment]
possible implementation:
I think we should (a) replace the report deletion button with a button marking the report as handled, (b) make the kick/ban buttons mark the report as handled and (c) add a button that warns the user (using a modal)

**Comment by MoonTM-GIT** [comment]
Yup, I like that

**Comment by DynxstyGIT** [comment]
Yup, imma work on this
