### ISSUE TITLE
Fix Custom Commands

### ISSUE THREAD

**Issue by DynxstyGIT** [Java-Discord/JavaBot#246]
I've noticed that `/customcommand create` & `/customcommand delete` do not respond to the slash command.

**Comment by MoonTM-GIT** [comment]
![image](https://user-images.githubusercontent.com/66334318/163382871-d940e657-9b39-4881-b52a-ba4c0f52a159.png)
Works for me

**Comment by DynxstyGIT** [comment]
Guess that was just temporary then
