### ISSUE TITLE
Add a "best answer" feature to QOTW

### ISSUE THREAD

**Issue by MoonTM-GIT** [Java-Discord/JavaBot#252]
Maybe we could add some sort of way to display the best answer to each week's QOTW.

This could work by adding another button or whatever to each submission that could mark it as the week's best. 

When this is done it could send it to `#❓︱question-of-the-week` allowing people that got the answer wrong or didn't know how to answer it to see

**Comment by danthe1st** [comment]
We could also send all accepted answers to the website automatically.
