### ISSUE TITLE
Add a `/move-conversation` feature, inspired by the Rust Community Discord

### ISSUE THREAD

**Issue by DynxstyGIT** [Java-Discord/JavaBot#259]
I guess this could be quite useful

![Screenshot_20220416-192133_Discord.png](https://user-images.githubusercontent.com/48297101/163685060-6342d650-5cbc-42e3-a1bc-8c6eef36cdd1.png)

![Screenshot_20220416-192120_Discord.png](https://user-images.githubusercontent.com/48297101/163685062-471d511b-a0ce-4e5c-ade9-8ce15cc2b1c3.png)

**Comment by danthe1st** [comment]
Here are some things that need to be thought of:
- Should this feature only be accessible by moderators or also via a community-voting?
- If this should be allowed to use by non-moderators, the channels conversations should be movable to should be restricted (we don't want people to move conversations into `#rules` etc)
- If messages should be copied, a webhook should probably be used for avoiding rate-limits and preserving user names
- If messages should be copied, `allowed_mentions` need to be set to all copied messages.
- It should probably also be possible to let the bot create a thread and move the conversation in there.
- If a conversation is moved to a help channel, it should be reserved. Who should the help channel be reserved for?
- It should probably not be possible to move conversations into reserved/dormant help channels.

**Comment by liquiddevelopmentnet** [comment]
I think, due to confusion and safety, this feature should be only available to moderators.

**Comment by DynxstyGIT** [comment]
Yeah, and I don't think it should copy the message.
