### ISSUE TITLE
QOTW Leaderboard improvements

### ISSUE THREAD

**Issue by DeveloperCallum** [Java-Discord/JavaBot#270]
**Is your feature request related to a problem? Please describe.**
we really need a use for QOTW points. I don't see the point of gathering pointless points plus, with the top leaders having a larger lead compared to recent people that have joined there isn't any competition to get the most points. people like @dan1st are always going to keep their lead considering he has gotten every point since rollout (or at least the majority)

**Describe the solution you'd like**
I think Question of the week leaderboard should show the top user (or top three) of each month (or each quarter) and reward that user with a role similar to the jam role we have/had. 

Excluding staff because its meaningless for us to have it as we are already high on the member list.

**Comment by danthe1st** [comment]
This has been implemented in some form over multiple PRs.

**Comment by DeveloperCallum** [comment]
> This has been implemented in some form over multiple PRs.

because it was an awesome idea
