### ISSUE TITLE
Use Webhooks for message links

### ISSUE THREAD

**Issue by MoonTM-GIT** [Java-Discord/JavaBot#278]
Use a webhook with the Users name & maybe profile picture of the User that sent the initial message

**Comment by danthe1st** [comment]
Note that this would require a webhook for every channel (with the alternative of creating a webhook for every message link and deleting it afterwards).

**Comment by liquiddevelopmentnet** [comment]
> Note that this would require a webhook for every channel (with the alternative of creating a webhook for every message link and deleting it afterwards).

I think that is the only opportunity to do this since the whole webhook messages would be changed with your alternative.

But creating one and deleting it afterwards should be no problem

**Comment by danthe1st** [comment]
I don't know the ratelimit of webhook creation but it might be possible to hit that for many links.
