### ISSUE TITLE
Bug: Changemymind api (nekobot.xyz) is crashing when too many characters are provided

### ISSUE THREAD

**Issue by liquiddevelopmentnet** [Java-Discord/JavaBot#295]
The API our Bot uses for the meme- image generation ([https://nekobot.xyz/](https://docs.nekobot.xyz/)) crashes with `HTTP CODE 501` when the text provided is too long, which results in a empty reply from the bot.

**Steps to reproduce**:
GET https://nekobot.xyz/api/imagegen?type=changemymind&text={Text with 2000 characters}

[File where this should be fixed](https://github.com/Java-Discord/JavaBot/blob/main/src/main/java/net/javadiscord/javabot/systems/commands/ChangeMyMindCommand.java)

**Comment by danthe1st** [comment]
Note that some unicode codepoints (like flagemojis) consist of multiple characters.
