### ISSUE TITLE
Add `/close` as an alias to `/unreserve`

### ISSUE THREAD

**Issue by danthe1st** [Java-Discord/JavaBot#317]
**Is your feature request related to a problem? Please describe.**
Many people attempt to use `/close` for unreserving a help channel instead of `/unreserve`.

**Describe the solution you'd like**
Add an alias `/close` to `/unreserve`. This should be possible by duplicating the command descriptor for `/unreserve` and renaming the copy to `close`.

With DIH4JDA, it might be necessary to create a subclass of the unreserve command class.

**Describe alternatives you've considered**
Everything could be kept as-is. This would keep people trying to use `/close` without success.

**Additional context**
https://discord.com/channels/648956210850299986/998717738572849216

**Comment by danthe1st** [comment]
With DIH4JDA, this could be done by subclassing `UnreserveCommand`.

**Comment by liquiddevelopmentnet** [comment]
What about adding `!close` and `!unreserve` as "alias" too then? Its very commonly used in help channels. Or at least automatically notify them that they need to use slash command ?

**Comment by danthe1st** [comment]
> What about adding `!close` and `!unreserve` as "alias" too then? Its very commonly used in help channels. Or at least automatically notify them that they need to use slash command ?
Discord already informs users when they try to use a command starting with a common prefix (e.g. `!`) that a matching slash command exists.
![image](https://user-images.githubusercontent.com/34687786/190689343-5211f391-5c6c-4086-91d8-6b06251fe61f.png)

**Comment by liquiddevelopmentnet** [comment]
Yeah true, I didn't think about that.
