### ISSUE TITLE
NullPointerException in MessageLinkListener

### ISSUE THREAD

**Issue by jasonlessenich** [Java-Discord/JavaBot#336]
I've noticed that there is an exception thrown for messages sent by "Webhook Users" (or in general system messages, which are not a member of the server)
So this just needs a null-check

![image](https://user-images.githubusercontent.com/48297101/182126977-2ac86875-ce2e-420c-adb0-7671c126e3c3.png)

**Comment by danthe1st** [comment]
Doesn't happen (any more) so it has probably been fixed at some point.
