### ISSUE TITLE
Add Redeployment Command

### ISSUE THREAD

**Issue by andrewlalis** [Java-Discord/JavaBot#35]
Add a `/redeploy` command, or something of that nature, which would automatically fetch the latest version of the bot's source from GitHub, compile it, and restart the bot using the new version.

**Comment by danthe1st** [comment]
The compilation could be done with GitHub Actions (thus uploading an artifact).

Maybe, it could even be pushed to the server the bot is running on automatically or it could fetch the latest artifact from GH Actions.

**Comment by danthe1st** [comment]
Actually, the workflow could trigger a webhook triggering the bot to fetch the newest version.
