### ISSUE TITLE
Add an API to query a member of the Java Discord

### ISSUE THREAD

**Issue by gsayson** [Java-Discord/JavaBot#451]
**Is your feature request related to a problem? Please describe.**
In a private correspondence between me and @liquiddevelopmentnet , we are discussing the creation of a specific website for voting on specific events, to mitigate voting by bots, and to humanize the process as much as possible.

Since we plan to restrict this to only Discord JUG members, we would need some way of confirming membership.

**Existing APIs and why they don't work**
The current endpoint for looking up users does not provide indication whether a member is in the Discord JUG.

**Describe the solution you'd like**
A new field in the `guilds/{id}/users/{userId}` endpoint, which indicates if the user is member of the guild or not. Some details like time joined may be added.

**Comment by danthe1st** [comment]
Closing that as we decided this wouldn't be needed.
