### ISSUE TITLE
Huge amount of scam links going undetected by Automod

### ISSUE THREAD

**Issue by sahilasopa** [Java-Discord/JavaBot#481]
Currently, Javabot relies on the file src/main/resources/spamLinks.txt for detecting scam links, but this file was updated 3 years ago, it should be considered to update the file to contain the newest URLs

**Comment by danthe1st** [comment]
I am unsure about the extent this file is actually used since the bot seems to [load the new version of the spam URLs on startup](https://github.com/Java-Discord/JavaBot/blob/main/src%2Fmain%2Fjava%2Fnet%2Fdiscordjug%2Fjavabot%2Fsystems%2Fmoderation%2FAutoMod.java#L66).

**Comment by sahilasopa** [comment]
> I am unsure about the extent this file is actually used since the bot seems to [load the new version of the spam URLs on startup](https://github.com/Java-Discord/JavaBot/blob/main/src%2Fmain%2Fjava%2Fnet%2Fdiscordjug%2Fjavabot%2Fsystems%2Fmoderation%2FAutoMod.java#L66).

it does load it in memory but it should not be tooooo big of a problem unless the bot is hosted on a toaster, and I skimmed  through the last few scam URLs sent on the server, the updated file in #482 seems to contain 9/10 of those URLs

**Comment by sahilasopa** [comment]
After doing a quick calculation, the file loads 195.73 KB of data in memory, which seems pretty reasonable.

**Comment by danthe1st** [comment]
> it does load it in memory but it should not be tooooo big of a problem unless the bot is hosted on a toaster, and I skimmed through the last few scam URLs sent on the server, the updated file in https://github.com/Java-Discord/JavaBot/pull/482 seems to contain 9/10 of those URLs

This is not about the amount of URLs. I was saying that I think that the bot actually doesn't use the file specified in the resources directory but automatically downloads the newest version and uses that.

**Comment by sahilasopa** [comment]
> > it does load it in memory but it should not be tooooo big of a problem unless the bot is hosted on a toaster, and I skimmed through the last few scam URLs sent on the server, the updated file in #482 seems to contain 9/10 of those URLs
> 
> This is not about the amount of URLs. I was saying that I think that the bot actually doesn't use the file specified in the resources directory but automatically downloads the newest version and uses that.

I missed that, well in that case the file should be removed from resources directory

**Comment by danthe1st** [comment]
If that file is actually unused, it might be good to completely delete it.

**Comment by danthe1st** [comment]
Originally, it was [loaded from resources](https://github.com/Java-Discord/JavaBot/commit/713c8d5cd9e946eb42261f2ca3ae3cb4bee9ce81#diff-fa6c26fc01113f712bb2dfe1c22d7074e8807e21ccec5c4cea58d4354818507d) but this [was changed to automatically fetch it](https://github.com/Java-Discord/JavaBot/commit/7a08d426f97b8d71da3d0c1aef82fa83a11b431a) and the file might be completely obsolete since then (unless it would be in use somewhere else and I didn't find anything with a full-text search on `spamLinks.txt`.

**Comment by danthe1st** [comment]
As described above, that file wasn't used and has even been removed by now.
