### ISSUE TITLE
Require Users to React to Message in Help-Guidelines Channel Before Being Allowed to Ask Question

### ISSUE THREAD

**Issue by andrewlalis** [Java-Discord/JavaBot#61]
As mentioned by dan1st, we should require that users read through the help guidelines before allowing them to ask a question in one of the help channels. We can do this by requiring users to react to a message in Help-Guidelines (or possibly other places as well), before being able to send messages or create threads in the help channels.

Once a user does the required actions, the should be given a role that permits them to use the help channels.

**Comment by Snape25** [comment]
@andrewlalis   Isnt reaction roles already implemented in the bot?

**Comment by andrewlalis** [comment]
> 
> 
> @andrewlalis Isnt reaction roles already implemented in the bot?

Already replied in Discord, but for parity, the reaction roles thing is quite old, and I think it's still dependent on a database.
