### ISSUE TITLE
Improve Antiraid to remove the usage of a Database

### ISSUE THREAD

**Issue by MoonTM-GIT** [Java-Discord/JavaBot#73]
The Antiraid feature is currently using MongoDB to store a list of potential bots.

We could improve antiraid by removing the database usage altogether

**Comment by DynxstyGIT** [comment]
This has been already been implemented. Although, I guess it could be improved by removing the usage of the Mongo Database.

https://github.com/Java-Discord/JavaBot/blob/8080075cbfb3acf36c077182db3f3e19f5d5da5a/src/main/java/com/javadiscord/javabot/other/ServerLock.java#L57-L66
