### ISSUE TITLE
Add /staff-apply Command to Apply for Staff Roles within Discord

### ISSUE THREAD

**Issue by andrewlalis** [Java-Discord/JavaBot#80]
The server is growing really fast, and we're gonna reach a point where we will really need to add more moderators and staff to help out. So I think it would be nice to add a `/staff-apply` command that users could use to apply to different staff roles.

Here's a list of the data which is collected on [our current airtable form](https://airtable.com/shrOSsNFREQFv8rRm):
- IRL name
- Discord tag
- Age
- Email
- Join date (this is sort of redundant since we have this info internally)
- Time zone
- Rank you are applying for
- Why did you join this server?
- Extra remarks

By doing it via slash commands, we can reduce this down to just the following fields:
- IRL name
- Age
- Email
- Time zone
- Rank you are applying for (can be a `ROLE` option)
- Extra remarks and whatnot

And then, the benefit is that we can view applications and accept/reject them automatically within Discord, and the bot can then automatically apply the necessary roles and send any welcome messages we'd want.

## Proposed Functionality
1. User submits an application via `/staff-apply <name> <age> <email> <timezone> <rank> <remarks>`
2. Existing staff members can view applications with `/staff-applications list [page=0]`, reject applications with `/staff-applications reject <id> <reason>`, or accept applications with `/staff-applications accept <id>`.
3. If rejected, the user is sent a message including the reason for the rejection.
4. If accepted, the user is given the specified role by the bot, and sent a message indicating that their application was successful. The bot can also send a message in a staff chat channel to welcome them to the team.
5. Applications older than (for example) 30 days can be automatically rejected with a `"Staff applications aren't needed at the moment"` message or something of that nature.

**Comment by MoonTM-GIT** [comment]
Sounds good 👍

> Existing staff members can view applications with /staff-applications list [page=0], reject applications with /staff-applications reject <id> <reason>, or accept applications with /staff-applications accept <id>.

I wouldn't say everyone with the `Staff` role should be able to do this, the `Application Review Team` Role would be good for this, although this will probably be configurable anyways.

> If accepted, the user is given the specified role by the bot, and sent a message indicating that their application was successful. The bot can also send a message in a staff chat channel to welcome them to the team.

This is usually the `Staff` role and the one the person applied to.

**Comment by DynxstyGIT** [comment]
yup, sounds awesome

> Rank you are applying for (can be a ROLE option)
we could just make an option with predefined choices for the different roles
(works just like the boolean option type)

**Comment by DynxstyGIT** [comment]
This has been moved to #212
